### ISSUE TITLE
Performance Issue - Google Page Speed

### ISSUE THREAD

**Issue by mmcgreg** [mmcgreg/web-design-2-independent-project#2]
Achieved yellow on mobile.
Only achieved yellow on desktop, needs green. Issue: Cumulative Layout Shift (?)

**Comment by thatkidmadrid** [comment]
![Screen Shot 2021-12-12 at 1 30 52 AM](https://user-images.githubusercontent.com/6340290/145702882-b598fa5e-80ac-4eb9-9b54-20bf69caeb7b.png)

Not sure what that was about, but testing now gives me green for desktop
