### ISSUE TITLE
Compression Issue

### ISSUE THREAD

**Issue by Cili23** [mmcgreg/web-design-2-independent-project#7]
Hey Morgan,

Your site is failing the compression test.
<img width="745" alt="Screen Shot 2021-12-11 at 12 11 19 PM" src="https://user-images.githubusercontent.com/77252057/145685424-bbd8ce16-4c43-4491-b92c-b89c9e96303f.png">

**Comment by thatkidmadrid** [comment]
We can ignore the compression warning because hosting with gh-pages we don't have the ability to enable gzip, but in the real world and using proper hosting services we can enable this for it to be green
